name: together_app
description: The Together App by CashlessSociety

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+10000

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.0.1
  flutter_screenutil: ^5.3.1
  google_fonts: ^2.3.1
  graphql_flutter: ^5.0.1
  graphql: ^5.0.1
  flutter_dotenv: ^5.0.2
  get: ^4.6.1
  provider: ^6.0.2
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  font_awesome_flutter: ^9.2.0
  flutter_typeahead: ^3.2.4
  keyboard_dismisser: ^2.0.1
  oktoast: ^3.1.5
  url_launcher: ^6.0.20
  detectable_text_field: ^2.0.3
  readmore: ^2.1.0
  path_provider: ^2.0.9
  amplify_flutter: ^0.4.0
  amplify_auth_cognito: ^0.4.0
  amplify_storage_s3: ^0.4.0
  image_picker: ^0.8.4+11
  image_cropper: ^1.5.0
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.0.0
  graphql_codegen: ^0.7.0-beta.6
  build_runner: ^2.0.3
  analyzer: ^2.0.0


dependency_overrides:
  font_awesome_flutter:
    path: font_awesome_flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
